### PR TITLE
moved covariates

### PR DESCRIPTION
**Pull request by mattsecrest**

### CODE REVIEW

**Comment by mattsecrest** [comment]
@gravesti if you agree we may as well start the micro versions

**Review by gravesti — APPROVED** [review]
looks good!

**Comment by gravesti** [comment]
> @gravesti if you agree we may as well start the micro versions

I think that the vbump job from [insightsengineering](https://github.com/insightsengineering/r.pkg.template/blob/main/.github/workflows/version-bump.yaml) works well to update version on merging.

**Comment by mattsecrest** [comment]
> 

Thanks Isaac! Yeah let's play around with it but for now happy to make it more manual...

**Pull request merged**
