### PR TITLE
simulate event data (#259)

### PR DESCRIPTION
**Pull request by gravesti**
Feature branch to add data simulation

Open issues
- [x] basic implementation
- [x] add tests
- [x] constructor for `DataSimEnrollment` objects
- [x] method to combine `create_baseline_object`s, maybe `c()`?
- [x] getter for `SimDataList@data_list[[i]]`
- [x] setter for additional transformations
- [x] check enrolment times are postive, add warning
- [x] only allow 1 drift?
---------

### CODE REVIEW

**Comment by mattsecrest** [comment]
@gravesti just wondering around naming. This is the UI in my understanding (prepping for investigator meeting):

psborrow2_data_simulation

Do you agree w/ this UI? If so, I wonder if `set_transformations()` and `set_event_dist()` make more sense? Same thought for the `DataSimEnrollment` constructor. Maybe `set_data_sim_enrollment()`?

**Comment by gravesti** [comment]
> @gravesti just wondering around naming. This is the UI in my understanding (prepping for investigator meeting):
> 
> Do you agree w/ this UI? If so, I wonder if `set_transformations()` and `set_event_dist()` make more sense? Same thought for the `DataSimEnrollment` constructor. Maybe `set_data_sim_enrollment()`?

- we could change `add_transformations` to `set_transformations`
- From this UI all the `set_*` functions are optional I think.
- Whereas an`DataSimEvent` object is required for `create_data_simulation()`. Maybe `event_dist()` should be `create_event_dist()`
- We have the DataSimEnrollment constructor for custom enrollment functions. These would still be used with `set_enrollment()`. I don't know if `set_data_sim_enrollment()` is friendlier?

**Comment by mattsecrest** [comment]
> > @gravesti just wondering around naming. This is the UI in my understanding (prepping for investigator meeting):
> > Do you agree w/ this UI? If so, I wonder if `set_transformations()` and `set_event_dist()` make more sense? Same thought for the `DataSimEnrollment` constructor. Maybe `set_data_sim_enrollment()`?
> 
> * we could change `add_transformations` to `set_transformations` 👍
> * From this UI all the `set_*` functions are optional I think.
> * Whereas an`DataSimEvent` object is required for `create_data_simulation()`. Maybe `event_dist()` should be `create_event_dist()`
> * We have the DataSimEnrollment constructor for custom enrollment functions. These would still be used with `set_enrollment()`. I don't know if `set_data_sim_enrollment()` is friendlier?

- 100% for `set_transformations`
- `create_event_dist` sounds good. maybe `specify_event_dist()` and `specify_baseline_vars()`?
- I would vote for `set_enrollment`

**Comment by mattsecrest** [comment]
- [ ] event dist --> `create_event_dist()`
- [ ] CRAN presubmit

**Review by mattsecrest — APPROVED** [review]
reviewed all PRs previously

**Pull request merged**
